email:
  login: suporte@dclick.com.br
  password: vanxhewjbhhuyoly
  receivers: lucas.rodrigues@dclick.com.br,guilherme.buzim@dclick.com.br,gerenciafinanceira@oceanica.com.br, leonardo.buzim@dclick.com.br
  receivers_2: lucas.rodrigues@dclick.com.br,leonardo.buzim@dclick.com.br
logLevel: 10


